const express = require("express");
const routes = express.Router();
const Genrecontroller = require("../controllers/Admin/Genre");

const gameGenres = [
  "Action",
  "Adventure",
  "Action-Adventure",
  "Role-Playing Game (RPG)",
  "Western RPG",
  "Japanese RPG (JRPG)",
  "Tactical RPG",
  "Roguelike",
  "Roguelite",
  "Metroidvania",
  "Simulation",
  "Life Simulation",
  "Farming Simulation",
  "Flight Simulator",
  "Train Simulator",
  "Vehicle Simulator",
  "Sports",
  "Traditional Sports",
  "Racing",
  "Arcade Racing",
  "Simulation Racing",
  "Combat Racing",
  "Strategy",
  "Real-Time Strategy (RTS)",
  "Turn-Based Strategy (TBS)",
  "4X",
  "Tower Defense",
  "MOBA",
  "Puzzle",
  "Physics-Based Puzzle",
  "Logic Puzzle",
  "Match-3",
  "Platformer",
  "2D Platformer",
  "3D Platformer",
  "Cinematic Platformer",
  "Shooter",
  "First-Person Shooter (FPS)",
  "Third-Person Shooter (TPS)",
  "Bullet Hell",
  "Rail Shooter",
  "Survival",
  "Horror",
  "Survival Horror",
  "Psychological Horror",
  "Stealth",
  "Sandbox",
  "Open World",
  "MMO",
  "MMORPG",
  "Idle / Incremental",
  "Rhythm",
  "Music / Dance",
  "Fighting",
  "2D Fighter",
  "3D Fighter",
  "Arena Fighter",
  "Beat 'em Up",
  "Brawler",
  "Party",
  "Trivia",
  "Card Game",
  "Collectible Card Game (CCG)",
  "Deck Builder",
  "Board Game",
  "Casino / Gambling",
  "Educational",
  "Visual Novel",
  "Interactive Fiction",
  "Text-Based",
  "Dating Sim",
  "Tycoon",
  "Business Simulation",
  "Management Sim",
  "City-Building",
  "God Game",
  "Experimental",
  "Narrative-Driven",
  "Walking Simulator",
  "Platform-Fighter",
  "Battle Royale",
  "Soulslike",
  "Extraction Shooter",
  "Metagame",
  "Looter Shooter",
  "Art Game",
  "Game Jam / Experimental Prototypes",
];

routes.post("/genre", async (req, res) => {
  const result = await Genrecontroller.addGenre(req.body);
  if (!result.success) {
    res.status(result.code).send(result.message);
  } else {
    res.send(result.data);
  }
});

module.exports = routes;
